Adds localization support for the mdx files and fix for the broken pages
romanr111/romanrud-blog pull request #28
Opened 2023-06-14 13:31 UTC by kaleemullahdev

2023-06-17 14:13 UTC, romanr111 requested changes
Please check.

2023-06-17 16:04 UTC, kaleemullahdev commented on src/@lekoarts/gatsby-theme-minimal-blog/components/homepage.tsx
> +import { jsx } from 'theme-ui';
Yes, it's possible that I've used nested keys for the tags in the 7-habit.json file.

2023-06-18 10:00 UTC, kaleemullahdev commented on src/@lekoarts/gatsby-theme-minimal-blog/components/homepage.tsx
>        <Listing posts={posts} showTags={false} />
Not for now. But I will look into this as well.

2023-06-18 10:00 UTC, kaleemullahdev commented on src/@lekoarts/gatsby-theme-minimal-blog/components/post.tsx
> -            <ItemTags tags={post.tags} />
I'll fix this. Thanks

2023-06-19 07:13 UTC, romanr111 commented on src/@lekoarts/gatsby-theme-minimal-blog/components/tag.tsx
>            {pageContext.name}
This one should return translated version of the tag as a h1
![Screenshot by Dropbox Capture](https://github.com/romanr111/romanrud-blog/assets/12322543/5dfe659b-99d3-44dd-aa0f-4a471f111b3a)

2023-06-19 07:26 UTC, romanr111 commented on src/@lekoarts/gatsby-theme-minimal-blog/components/tags.tsx
>        </Heading>
This one should return translated version of the tag as a h1
![Screenshot by Dropbox Capture](https://github.com/romanr111/romanrud-blog/assets/12322543/34664f21-ebd2-473b-bec7-18c4cc165c73)

2023-06-19 07:26 UTC, romanr111 commented on src/@lekoarts/gatsby-theme-minimal-blog/components/tags.tsx
> +export const Head: HeadFC = () => <Seo title="Теги" />;
SEO title as well needs to be translated.

2023-06-19 07:31 UTC, romanr111 commented on src/@lekoarts/gatsby-theme-minimal-blog/components/page.tsx
> +  <Seo title={page.title} description={page.excerpt} />
@kaleemullahdev Page metedata needs to be translated as well;
![Screenshot by Dropbox Capture](https://github.com/romanr111/romanrud-blog/assets/12322543/b448d1ec-614a-4687-bd85-1c4aa086f2b6)

2023-06-19 07:35 UTC, romanr111 commented on src/@lekoarts/gatsby-theme-minimal-blog/components/post.tsx
> +  const title = isBookReview
Post metadata needs to be translated as well.
![Screenshot by Dropbox Capture](https://github.com/romanr111/romanrud-blog/assets/12322543/85ba1934-7be5-4fce-afd5-503120ad5289)
![Screenshot by Dropbox Capture](https://github.com/romanr111/romanrud-blog/assets/12322543/c03dbf17-2051-4d7c-8332-32f35ec435b4)

2023-06-19 08:57 UTC, romanr111 commented on content/posts/7-habits/index.mdx
> +<Translation
Here I was able to create PR into your branch.
https://github.com/kaleemullahdev/romanrud-blog/pull/1

2023-06-20 07:23 UTC, kaleemullahdev commented
Great work @romanr111. I have one small suggestion. Instead of directly passing the markdown content to the ReactMarkdown component, consider utilizing the children prop. This will make the component more flexible, as it will allow us to customize the content using component props in the future. While this change is not necessary at the moment, it's something I'm considering for future enhancements. Thank you for your understanding.

2023-06-22 06:06 UTC, romanr111 approved these changes
Looks great!

2023-06-22 15:10 UTC, merged